// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TY.test1.Models.EFModels;

public partial class MyofficeExcuteionLog
{
    public int DeLogAuthId { get; set; }

    public string DeLogStoredPrograms { get; set; }

    public Guid DeLogGroupId { get; set; }

    public bool DeLogIsCustomDebug { get; set; }

    public string DeLogExecutionProgram { get; set; }

    public string DeLogExecuteionInfo { get; set; }

    public bool DeLogVerifyNeeded { get; set; }

    public DateTime ExelogNowdatetime { get; set; }
}